acl/urls.py
from acl.views import *
from django.urls import path

app_name = "acl"
urlpatterns = [
    path("", home_page, name="home"),
    path("login/", login, name="login"),
    path("list_content/", content_listing_page, name="content-listing"),

    path("create_user/", user_creation_page, name="user-creation"),
    path("user_detail/<str:pk>/", user_detail_page, name="user-details"),
    path("user_update/<str:pk>/", user_update_page, name="user-updating"),

    path("create_group/", group_creation_page, name="group-creation"),
    path("group_detail/<str:pk>/", group_detail_page, name="group-details"),
    path("group_update/<str:pk>/", group_update_page, name="group-updating"),

    path("logout/", logout, name="user-logout")
]

permission/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('api/', include('restapi.urls')),
]
urlpatterns += i18n_patterns(
    path("", include("acl.urls")),
    path('admin/', admin.site.urls),
    path('resource/', include("resource.urls")),

)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resource/urls.py
from django.urls import path
from resource.views import *

app_name = "resource"
urlpatterns = [
    path("", HomePage.as_view(), name="resource-homepage")
]

acl/models.py
from django.db import models


class Permission(models.Model):
    """
        This is where all permissions that we use in our system defined
    """
    permission = models.CharField(max_length=100, unique=True)
    description = models.CharField(max_length=250)

    def __str__(self):
        return self.description


class User(models.Model):
    """
        This is a user model with role and specific permission tied
        to them at the user creation
    """
    ROLES = (
        ('admin', "Admin"),
        ('user', 'User')
    )
    username = models.CharField(max_length=100, unique=True)
    email = models.EmailField(max_length=150, unique=True)
    password = models.CharField(max_length=150, default='1234')
    role = models.CharField(max_length=6, choices=ROLES)
    groups = models.ManyToManyField("Group", related_name="members", blank=True, null=True)
    permissions = models.ManyToManyField(Permission, related_name="individual_perm", blank=True, null=True)
    picture = models.ImageField(upload_to='media/images/', default='media/images/default_profile_pic.jpg')
    in_trash = models.BooleanField(default=False)

    def __str__(self):
        return self.username


class Group(models.Model):
    """
        It's a group that has specific permission from Permission table
        and any user placed in this group shares the same permissions
    """

    name = models.CharField(max_length=100)
    permissions = models.ManyToManyField(Permission, related_name="group_perm", blank=True, null=True)

    def __str__(self):
        return self.name


class TestModel(models.Model):

    name = models.CharField(max_length=100)
    change = models.CharField(max_length=200)
    remote = models.CharField(max_length=300)

    def __str__(self):
        return self.name + " " + self.change

acl/views.py
from django.shortcuts import render, redirect, reverse
from acl.models import Group
from django.contrib import messages

from .include import *

from django.utils.translation import gettext_lazy as _

# Create your views here.


def translate(request):

    context = {
        'message': 'trans'
    }
    return render(request, 'acl/translations.html', context)


def home_page(request):
    add_permission_to_db()
    _user = logged_user(request)
    permissions = extract_permissions(_user)

    context = {
        "is_home_page": True,
        'permissions': permissions,
        'logged': {
            'user': User.objects.filter(
                email=request.session.get('email', '')
            ).first(),
            'email': request.session.get('email', ''),
            'username': request.session.get('username', '')
        }
    }
    return render(request, 'acl/navbar.html', context)


def login(request):
    _user = logged_user(request)
    permissions = extract_permissions(_user)

    if request.method == "POST":
        email = request.POST.get('email')
        password = request.POST.get("password")

        if email and password:
            _usr = User.objects.filter(email=email, password=password)
            if _usr.exists():
                request.session["username"] = _usr[0].username
                request.session['email'] = _usr[0].email
                messages.success(request, "Welcome, successfully logged in.")
                return redirect(reverse('acl:content-listing') + "?list=users")
            else:
                messages.error(request, "User with this credential doesn't exist!")
        else:
            messages.error(request, "Please Provide both email and password!")
    context = {
        'permissions': permissions,
        'logged': {
            'user': User.objects.filter(
                email=request.session.get('email', '')
            ).first(),
            'email': request.session.get('email', ''),
            'username': request.session.get('username', '')
        }
    }
    return render(request, 'acl/login.html', context)


def content_listing_page(request):
    _user = logged_user(request)
    permissions = extract_permissions(_user)
    groups = Group.objects.all()

    page = request.GET.get('list')

    context = {
        'page': page,
        'users': User.objects.all(),
        'groups': groups,
        'permissions': permissions,
        'logged': {
            'user': User.objects.filter(
                email=request.session.get('email', '')
            ).first(),
            'email': request.session.get('email', ''),
            'username': request.session.get('username', '')
        }
    }
    return render(request, 'acl/list_content.html', context)


def user_creation_page(request):
    _user = logged_user(request)
    permissions = extract_permissions(_user)
    list_groups = Group.objects.all()
    list_permissions = Permission.objects.all()
    group_of_perm = get_grouped_permissions()

    if request.method == "POST":
        username = request.POST.get('username')
        email = request.POST.get('email')
        role = request.POST.get('role')
        groups = request.POST.getlist('groups')
        selected_perm = request.POST.getlist('selected_perm')

        new_user = User.objects.create(
            username=username,
            email=email,
            role=role,
        )
        if role == 'user':
            for perm_name in selected_perm:
                new_user.permissions.add(list_permissions.get(permission__contains=perm_name))
        else:
            for perm in list_permissions:
                new_user.permissions.add(perm)
        for group in groups:
            new_user.groups.add(list_groups.get(id=group))
        messages.success(request, "User successfully created.")
        new_user.save()

    context = {
        'permissions': permissions,
        'group_of_perm': group_of_perm,
        'groups': list_groups,
        'logged': {
            'user': User.objects.filter(
                email=request.session.get('email', '')
            ).first(),
            'email': request.session.get('email', ''),
            'username': request.session.get('username', '')
        }
    }
    return render(request, 'acl/user_creation.html', context)


def group_creation_page(request):
    permissions = extract_permissions(logged_user(request))
    group_of_perm = get_grouped_permissions()
    list_permissions = Permission.objects.all()

    if request.method == "POST":
        group_name = request.POST.get('group_name')
        selected_perm = request.POST.getlist('selected_perm')

        new_group = Group.objects.create(
            name=group_name,
        )
        for perm_name in selected_perm:
            new_group.permissions.add(list_permissions.get(permission__contains=perm_name))
        new_group.save()
        messages.success(request, "Group successfully created.")

    context = {
        'permissions': permissions,
        'group_of_perm': group_of_perm,
        'logged': {
            'user': User.objects.filter(
                email=request.session.get('email', '')
            ).first(),
            'email': request.session.get('email', ''),
            'username': request.session.get('username', '')
        }
    }
    return render(request, 'acl/group_creation.html', context)


def user_detail_page(request, pk):
    permissions = extract_permissions(logged_user(request))
    user = User.objects.get(id=pk)

    context = {
        'permissions': permissions,
        'user': user,
        'logged': {
            'user': User.objects.filter(
                email=request.session.get('email', '')
            ).first(),
            'email': request.session.get('email', ''),
            'username': request.session.get('username', '')
        }
    }
    return render(request, 'acl/detail_user.html', context)


def group_detail_page(request, pk):
    permissions = extract_permissions(logged_user(request))
    group = Group.objects.get(id=pk)

    context = {
        'permissions': permissions,
        'group': group,
        'logged': {
            'user': User.objects.filter(
                email=request.session.get('email', '')
            ).first(),
            'email': request.session.get('email', ''),
            'username': request.session.get('username', '')
        }
    }
    return render(request, 'acl/group_detail.html', context)


def group_update_page(request, pk):
    permissions = extract_permissions(logged_user(request))
    group_of_perm = get_grouped_permissions()
    group = Group.objects.get(id=pk)
    list_groups = Group.objects.all()

    if request.method == "POST":
        group_name = request.POST.get('group_name')
        selected_perm = request.POST.getlist('selected_perm')

        group.permissions.clear()
        group.name = group_name
        group.permissions.set(selected_perm)
        messages.info(request, "Group information successfully updated.")
        group.save()

        return redirect(reverse('acl:group-details', args=pk))

    context = {
        'updated_group': group,
        'list_groups': list_groups,
        'group_of_perm': group_of_perm,
        'permissions': permissions,
        'logged': {
            'user': User.objects.filter(
                email=request.session.get('email', '')
            ).first(),
            'email': request.session.get('email', ''),
            'username': request.session.get('username', '')
        }
    }
    return render(request, 'acl/update_group.html', context)


def user_update_page(request, pk):
    group_of_perm = get_grouped_permissions()
    user = User.objects.get(id=pk)
    permissions = extract_permissions(user)
    list_groups = Group.objects.all()

    if request.method == "POST":
        username = request.POST.get('username')
        email = request.POST.get('email')
        role = request.POST.get('role')
        groups = request.POST.getlist('groups')
        selected_perm = request.POST.getlist('selected_perm')

        user.permissions.remove()
        user.groups.clear()

        user.username = username
        user.email = email
        user.role = role
        user.groups.set(groups)
        user.permissions.set(selected_perm)

        if role == 'admin':
            user.permissions.set(Permission.objects.all())
        messages.info(request, "User information successfully updated.")
        user.save()

        return redirect(reverse('acl:user-details', args=pk))

    context = {
        'user': user,
        'list_groups': list_groups,
        'group_of_perm': group_of_perm,
        'permissions': permissions,
        'logged': {
            'user': User.objects.filter(
                email=request.session.get('email', '')
            ).first(),
            'email': request.session.get('email', ''),
            'username': request.session.get('username', '')
        }
    }
    return render(request, 'acl/update_user.html', context)


def user_delete(request, pk):
    user = User.objects.get(id=pk)

    # ToDo implement safe delete later
    user.delete()
    return redirect(reverse('acl:content-listing') + 'list=users')


def group_delete(request, pk):
    group = Group.objects.get(id=pk)

    group.delete()
    return redirect(reverse('acl:content-listing') + 'list=groups')


def logout(request):
    _user = logged_user(request)
    messages.info(request, "Successfully logged out.")
    request.session.pop('email', None)
    request.session.pop('username', None)

    return redirect(reverse('acl:login'))

templates/acl/detail_user.html
{% load i18n %}
{% include "acl/navbar.html" %}

{% block container %}
    <div class="container">
        <h2>{% translate 'User Details' %}</h2>
        <div class="card">
            <div class="card-body">
            <a href="{% url 'acl:content-listing' %}?list=users" class="btn btn-primary btn-sm float-right">{% translate 'Take me back' %}</a>
                <p class="card-text">{% translate 'username' %}: {{ user.username }}</p>
                <p class="card-text">{% translate 'email' %}: {{ user.email }}</p>
                <h5 class="card-subtitle mb-2 ">{% translate 'Permissions' %}:</h5>
                <ul class="">
                    {%  for perm in user.permissions.select_related %}
                        <li>{{ perm }}</li>
                    {% endfor %}
                    {%  for group in user.groups.select_related %}
                        {%  for perm in group.permissions.select_related %}
                            <li>{{ perm }}</li>
                        {% endfor %}

                    {% endfor %}
                </ul>
                <h5 class="card-subtitle mb-2 ">{% translate 'Groups' %}:</h5>
                <ul class="">
                    {%  for group in user.groups.select_related %}
                        <li >{{ group.name }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

templates/acl/group_creation.html
{% load i18n %}
{% include "acl/navbar.html" %}

{% block container %}

    <div class="container">
        <h2>{% translate 'Group Creation Form' %}</h2>
        <form action="" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="group_name_id">{% translate 'Group Name' %}:</label>
                <input type="text" class="form-control" name="group_name" id="group_name_id" placeholder="{% translate 'Enter group name' %}" required>
            </div>
            <div class="form-group">
                <label for="permissions">{% translate 'Permissions' %}:</label>
                <div class="row">
                    {% for group, perm in group_of_perm.items %}
                        <div class="col-md-4 mt-3">
                            <div class="card-title font-weight-bold">{{ group }}</div>
                            {% for p in perm %}
                                <div class="form-check">
                                   <input
                                        type="checkbox"
                                        class="form-check-input"
                                        id="p.permission"
                                        name="selected_perm"
                                        value="{{ p.permission }}"
                                    >
                                    <label class="form-check-label" for="permission3">{{ p }}</label>
                                </div>
                            {% endfor %}

                        </div>
                    {% endfor %}

                </div>
            </div>
            <button type="submit" class="btn btn-primary">{% translate 'Create Group' %}</button>
        </form>
    </div>

{% endblock %}

templates/acl/group_detail.html
{% load i18n %}
{% include "acl/navbar.html" %}

{% block container %}
    <div class="container">
        <h2>{% translate 'Group Details' %}</h2>
        <div class="card">
            <div class="card-body">
                <a href="{% url 'acl:content-listing' %}?list=groups" class="btn btn-primary btn-sm float-right">{% translate 'Take me back' %}</a>
                <p class="card-text">{% translate 'Group name' %}: {{ group.name }}</p>
                <h5 class="card-subtitle mb-2 "> {% translate 'Group permissions' %}:</h5>
                <ul class="">
                    {%  for perm in group.permissions.select_related %}
                        <li>{{ perm }}</li>
                    {% endfor %}

                </ul>
                <h5 class="card-subtitle mb-2 ">{% translate 'Users in the group' %}:</h5>
                <ul class="">
                    {%  for user in group.members.all %}
                        <li>{{ user }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

templates/acl/list_content.html
{% load i18n %}
{% include "acl/navbar.html" %}

{% block container %}
    <div class="container">

    {% if page == 'users' %}
        <h2>
            {% translate 'User List' %}
            <a href="?list=groups" class="btn btn-primary float-right">{% translate 'List Groups' %}</a>
        </h2>
        <small>{% translate 'We display 4 permission only here, check detail for more' %}.</small>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>#</th>
                    <th>{% translate 'Username' %}</th>
                    <th>{% translate 'Email' %}</th>
                    <th>{% translate 'Permission' %}</th>
                    <th>{% translate 'Groups' %}</th>
                    <th>{% translate 'Actions' %}</th>
                </tr>
            </thead>
            <tbody>
            {% if 'view_users' in permissions %}
                {% for user in users %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ user.username }}</td>
                    <td>{{ user.email }}</td>
                    <td>
                        {%  for perm in user.permissions.select_related|slice:":2" %}
                            <li>{{ perm }}</li>
                        {% endfor %}
                        {%  for group in user.groups.select_related|slice:":2" %}
                            {%  for perm in group.permissions.select_related|slice:":2" %}
                                <li>{{ perm }}</li>
                            {% endfor %}
                        {% endfor %}
                    </td>
                    <td>
                        {%  for group in user.groups.select_related %}
                            <li>{{ group }}</li>
                        {% endfor %}
                    </td>
                    <td>
{#                        <a href="{% url 'edit_user' user.id %}" class="btn btn-primary">Edit</a>#}
{#                        <a href="{% url 'delete_user' user.id %}" class="btn btn-danger">Delete</a>#}

                        <a href="{% url 'acl:user-updating' user.id %}" class="btn btn-primary {% if not 'change_users' in permissions %} disabled {% endif %}">{% translate 'Update' %}</a>
                        <a href="{% url 'acl:user-details' user.id %}" class="btn btn-success {% if not 'view_users' in permissions %} disabled {% endif %}">{% translate 'View' %}</a>
                        <a href="" class="btn btn-danger {% if not 'delete_users' in permissions %} disabled {% endif %}">{% translate 'Delete' %}</a>
                    </td>
                </tr>
                {% endfor %}
            {% else %}
                <p class="text-danger font-weight-bold">{% translate "You don't have a permission to view users" %}</p>
            {% endif %}
            </tbody>
        </table>
    {% endif %}
    {% if page == 'groups' %}
        <table class="table table-striped">
        <h2>
            {% translate 'Group List' %}
            <a href="?list=users" class="btn btn-primary float-right">{% translate 'List Users' %}</a>

        </h2>
        <small>{% translate 'We display 4 permission only here, check detail for more' %}</small>
            <thead>
                <tr>
                    <th>#</th>
                    <th>{% translate 'Name' %}</th>
                    <th>{% translate 'Permission' %}</th>
                    <th>{% translate 'Actions' %}</th>
                </tr>
            </thead>
            <tbody>
            {% if 'view_groups' in permissions %}
                {% for group in groups %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ group.name }}</td>

                    <td>
                        {%  for perm in group.permissions.select_related|slice:':4' %}
                            <li>{{ perm }}</li>
                        {% endfor %}
                    </td>
                    <td>

                        <a href="{% url 'acl:group-updating' group.id %}" class="btn btn-primary {% if not 'change_users' in permissions %} disabled {% endif %}">{% translate 'Update' %}</a>
                        <a href="{% url 'acl:group-details' group.id %}" class="btn btn-success {% if not 'view_users' in permissions %} disabled {% endif %}">{% translate 'View' %}</a>
                        <a href="" class="btn btn-danger {% if not 'delete_users' in permissions %} disabled {% endif %}">{% translate 'Delete' %}</a>
                    </td>
                </tr>
                {% endfor %}
            {% else %}
                <p class="text-danger font-weight-bold">{% translate "You don't have a permission to view groups" %}</p>
            {% endif %}
            </tbody>
        </table>
    {% endif %}
    </div>
{% endblock %}

templates/acl/login.html
{% load i18n %}
{% include "acl/navbar.html" %}

{% block container %}
    <div class="container">
    <h2>{% translate "Login Page" %}</h2>
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="email">{% translate 'Email' %}:</label>
            <input type="email" class="form-control" name="email" placeholder="{% translate 'Enter email' %}" required>
        </div>
        <div class="form-group">
            <label for="password">{% translate 'Password' %}:</label>
            <input type="password" class="form-control" name="password" placeholder="{% translate 'Enter password' %}" required>
        </div>
        <button type="submit" class="btn btn-primary">{% translate 'Login' %}</button>
    </form>
    </div>
{% endblock %}

templates/acl/navbar.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Duo | Advanced Django Tutorial</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'acl:home' %}">Duo</a>

    <span class="text-primary">session: <span class="text-success"> {{ logged.email }}</span></span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'acl:content-listing' %}?list=users"> {% translate 'Home' %} </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if not 'add_users' in permissions %} disabled {% endif %}" href="{% url 'resource:resource-homepage' %}"> {% translate 'Add Resource' %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if not 'add_users' in permissions %} disabled {% endif %}" href="{% url 'acl:user-creation' %}"> {% translate 'Create User' %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if not 'add_groups' in permissions %} disabled {% endif %}" href="{% url 'acl:group-creation' %}">{% translate 'Create Group' %}</a>
            </li>
            {% if logged.user %}
                <li class="nav-item">
                    <div class="dropdown show">
                      <a class="btn  dropdown-toggle" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {% translate 'Account' %}
                      </a>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                          <a class="dropdown-item" style="width: 200px;">
                            <a class="nav-link" href="#" >
                                <img src="{{ logged.user.picture.url }}" alt="Profile Picture" class="rounded-circle" width="80" height="80">
                                {{ logged.user.username }}
                            </a>
                            <a class="dropdown-item" href="#">{% translate 'Profile' %}</a>
                            <a class="dropdown-item" href="#">{% translate 'Settings' %}</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'acl:user-logout' %}">{% translate 'Logout' %}</a>

                          </a>
                      </div>
                    </div>
                </li>
            {% endif %}

            <li class="nav-item">
                <div class="dropdown show">
                  <a class="btn  dropdown-toggle" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {% translate 'Languages' %}
                  </a>

                  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                      {% get_available_languages as LANGUAGES %}
                      {% get_language_info_list for LANGUAGES as langs %}
                      {% for lang in langs %}
                        <a class="dropdown-item" href="/{{ lang.code }}/">{{ lang.name_local }}</a>
                      {% endfor %}
                  </div>
                </div>
            </li>
        </ul>
    </div>
</nav>

{% block container %}
    {% include 'includes/messages.html' %}
    {% if is_home_page %}
        <div class="container">
            <h2>{% translate "Login Page" %}</h2>
            <form action="login/" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="email">{% translate 'Email' %}:</label>
                    <input type="email" class="form-control" name="email" placeholder="{% translate 'Enter email' %}" required>
                </div>
                <div class="form-group">
                    <label for="password">{% translate 'Password' %}:</label>
                    <input type="password" class="form-control" name="password" placeholder="{% translate 'Enter password' %}" required>
                </div>
                <button type="submit" class="btn btn-primary">{% translate 'Login' %}</button>
            </form>
        </div>
    {% endif %}
{% endblock %}


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.13.3/js/standalone/selectize.min.js"></script>

</body>
</html>

templates/acl/update_group.html
{% load i18n %}
{% include "acl/navbar.html" %}

{% block container %}

    <div class="container">
        <h2>{% translate 'Group Updation Form' %}</h2>
        <form action="" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="group_name_id">{% translate 'Group Name' %}:</label>
                <input type="text" class="form-control" value="{{ updated_group.name }}" name="group_name" id="group_name_id" placeholder="{% translate 'Enter group name' %}" required>
            </div>
            <div class="form-group">
                <label for="permissions">{% translate 'Permissions' %}:</label>
                <div class="row">
                    {% for group, perm in group_of_perm.items %}
                        <div class="col-md-4 mt-3">
                            <div class="card-title font-weight-bold">{{ group }}</div>
                            {% for p in perm %}
                                <div class="form-check">
                                   <input
                                        type="checkbox"
                                        class="form-check-input"
                                        name="selected_perm"
                                        value="{{ p.id }}"
                                        {% if p in updated_group.permissions.select_related %}
                                            checked
                                        {% endif %}
                                    >
                                    <label class="form-check-label" for="permission3">{{ p }}</label>
                                </div>
                            {% endfor %}

                        </div>
                    {% endfor %}

                </div>
            </div>
            <button type="submit" class="btn btn-primary">{% translate 'Update Group' %}</button>
        </form>
    </div>

{% endblock %}